name: storyio
description: "A Story App Flutter Project"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.18.1
  http: ^1.2.0
  provider: ^6.1.1
  location: ^5.0.3
  geocoding: ^2.1.1
  app_settings: ^5.1.1
  image_picker: ^1.0.7
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  google_maps_flutter: ^2.5.3
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  flutter_image_compress: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/loading_image.gif
