name: storyio
description: "A Story App Flutter Project"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  http: ^1.2.0
  provider: ^6.1.1
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/loading_image.gif
